[package]
name = "rust_supabase_sdk"
version = "0.2.12"
edition = "2021"
description = "An SDK kit for SupaBase so that Rust lovers can use SupaBase with the low level abstracted away. If you want new features tell me and I'll add them."
license = "MIT"
authors = ["Lachy Hislop lachie.hislop@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.22", features = ["json"] }
serde_json = "1.0.140"
serde = { version = "1.0.140", features = ["derive"] }
dotenv = "0.15.0"
tokio = { version = "1.46.1", features = ["full"] }
rand = "0.9.1"
uuid = { version = "1.17.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
chrono = "0.4.41"
urlencoding = "2.1.3"
url="2.5.4"