[package]
name = "rust_supabase_sdk"
version = "0.1.5"
edition = "2021"
description = "An SDK kit for SupaBase so that Rust lovers can use SupaBase with the low level abstracted away. If you want new features tell me and I'll add them."
license = "MIT"
authors = ["Lachy Hislop lachie.hislop@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.108"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
chrono = "0.4.31"
urlencoding = "2.1.3"