//! Parse PostgREST's OpenAPI introspection document and emit Rust row structs.
//!
//! PostgREST returns Swagger 2.0 from `GET /rest/v1/?apikey=<key>`. Each
//! exposed table appears under `definitions`, with a `properties` map and an
//! optional `required` list:
//!
//! ```json
//! { "swagger": "2.0",
//!   "definitions": {
//!     "users": {
//!       "required": ["id"],
//!       "properties": {
//!         "id":         { "format": "uuid",                       "type": "string" },
//!         "email":      { "format": "text",                       "type": "string" },
//!         "created_at": { "format": "timestamp with time zone",   "type": "string" }
//!       }
//!     }
//!   }
//! }
//! ```
//!
//! We translate `format` (preferred) and fall back to `type` when the format
//! is unknown. Columns absent from `required` are wrapped in `Option<T>`.

use std::collections::BTreeMap;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct OpenApi {
    #[serde(default)]
    pub definitions: BTreeMap<String, TableDef>,
}

#[derive(Debug, Deserialize)]
pub struct TableDef {
    #[serde(default)]
    pub required: Vec<String>,
    #[serde(default)]
    pub properties: BTreeMap<String, ColumnDef>,
}

#[derive(Debug, Deserialize, Default)]
pub struct ColumnDef {
    #[serde(default)]
    pub format: Option<String>,
    #[serde(default, rename = "type")]
    pub kind: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
}

/// Codegen settings, surfaced as CLI flags.
#[derive(Debug, Clone)]
pub struct Options {
    /// Optional schema label baked into the generated docs / `Row::SCHEMA`.
    pub schema: String,
    /// Optional table allow-list. Empty = emit every discovered table.
    pub only: Vec<String>,
    /// Optional table deny-list.
    pub exclude: Vec<String>,
    /// Whether to use `chrono` types for timestamp/date columns. When `false`,
    /// timestamps are emitted as `String`.
    pub chrono: bool,
    /// Whether to use `uuid::Uuid` for `uuid`-format columns. When `false`,
    /// they are emitted as `String`.
    pub uuid_type: bool,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            schema: "public".to_string(),
            only: Vec::new(),
            exclude: Vec::new(),
            chrono: true,
            uuid_type: false,
        }
    }
}

/// Generate the contents of a Rust module from a parsed OpenAPI document.
pub fn emit(api: &OpenApi, opts: &Options) -> String {
    let mut out = String::new();
    out.push_str(HEADER);

    let mut tables: Vec<(&String, &TableDef)> = api
        .definitions
        .iter()
        .filter(|(name, _)| {
            if !opts.only.is_empty() && !opts.only.iter().any(|p| p == *name) {
                return false;
            }
            !opts.exclude.iter().any(|p| p == *name)
        })
        .collect();
    tables.sort_by(|a, b| a.0.cmp(b.0));

    for (table_name, def) in tables {
        emit_table(&mut out, &opts.schema, table_name, def, opts);
    }

    out
}

const HEADER: &str = "//! Auto-generated by `cargo supabase gen types`. DO NOT EDIT.
//!
//! Re-generate with the same command after applying a migration.

#![allow(clippy::module_name_repetitions, dead_code)]
#![allow(non_camel_case_types, non_snake_case)]

use rust_supabase_sdk::{postgrest::Column, Row};
use serde::{Deserialize, Serialize};

";

fn emit_table(out: &mut String, schema: &str, table: &str, def: &TableDef, opts: &Options) {
    let struct_name = to_struct_name(table);

    out.push_str(&format!("/// Row of `{schema}.{table}`.\n"));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {struct_name} {{\n"));

    let mut columns: Vec<(&String, &ColumnDef)> = def.properties.iter().collect();
    columns.sort_by(|a, b| a.0.cmp(b.0));

    let mut column_names: Vec<String> = Vec::with_capacity(columns.len());
    for (col_name, col) in &columns {
        let rust_ty = map_type(col, opts);
        let optional = !def.required.iter().any(|r| r == *col_name);
        let final_ty = if optional {
            format!("Option<{rust_ty}>")
        } else {
            rust_ty
        };

        if let Some(desc) = &col.description {
            for line in desc.lines() {
                out.push_str(&format!("    /// {line}\n"));
            }
        }
        let safe = to_field_name(col_name);
        if safe != *col_name.as_str() {
            out.push_str(&format!("    #[serde(rename = \"{col_name}\")]\n"));
        }
        out.push_str(&format!("    pub {safe}: {final_ty},\n"));
        column_names.push((*col_name).clone());
    }

    out.push_str("}\n\n");

    out.push_str(&format!("impl Row for {struct_name} {{\n"));
    out.push_str(&format!("    const TABLE: &'static str = \"{table}\";\n"));
    out.push_str(&format!(
        "    const SCHEMA: Option<&'static str> = Some(\"{schema}\");\n"
    ));
    out.push_str("    const COLUMNS: &'static [&'static str] = &[");
    for (i, c) in column_names.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push('"');
        out.push_str(c);
        out.push('"');
    }
    out.push_str("];\n");
    out.push_str("}\n\n");

    // ------------------------------------------------------------
    // Typed column constants:
    //   impl Posts {
    //       pub const status: Column<Posts, String> = Column::new("status");
    //       ...
    //   }
    // ------------------------------------------------------------
    out.push_str(&format!(
        "#[allow(non_upper_case_globals)]\nimpl {struct_name} {{\n"
    ));
    for (col_name, col) in &columns {
        let rust_ty = map_type(col, opts);
        let optional = !def.required.iter().any(|r| r == *col_name);
        let final_ty = if optional {
            format!("Option<{rust_ty}>")
        } else {
            rust_ty
        };
        let safe = to_field_name(col_name);
        out.push_str(&format!(
            "    pub const {safe}: Column<{struct_name}, {final_ty}> = Column::new(\"{col_name}\");\n"
        ));
    }
    out.push_str("}\n\n");
}

/// Map a PostgREST column descriptor to a Rust type name.
fn map_type(col: &ColumnDef, opts: &Options) -> String {
    let fmt = col.format.as_deref().unwrap_or("").trim();
    let kind = col.kind.as_deref().unwrap_or("").trim();

    // Arrays — kind is "array", format describes the element type.
    // Pass "" as the element-level `kind` so that the string-type guard
    // (`kind == "string"`) does not prevent "text", "varchar" etc. from
    // resolving correctly inside the element.
    if kind == "array" {
        let elem_fmt = fmt;
        let inner = map_scalar_format(elem_fmt, "string", opts);
        return format!("Vec<{inner}>");
    }

    map_scalar_format(fmt, kind, opts)
}

fn map_scalar_format(format: &str, kind: &str, opts: &Options) -> String {
    let stripped = format.trim_start_matches("array of ").trim();
    match stripped {
        // Integers
        "smallint" | "int2" => "i16".into(),
        "integer" | "int" | "int4" | "serial" => "i32".into(),
        "bigint" | "int8" | "bigserial" => "i64".into(),
        // Floats / numeric
        "real" | "float4" => "f32".into(),
        "double precision" | "float8" => "f64".into(),
        "numeric" | "decimal" | "money" => "f64".into(),
        // Booleans
        "boolean" | "bool" => "bool".into(),
        // Strings
        "text" | "character varying" | "varchar" | "character" | "bpchar" | "name" | "citext"
        | "" if kind == "string" || (kind.is_empty() && stripped.is_empty()) => "String".into(),
        // Times
        "timestamp with time zone" | "timestamptz" => {
            if opts.chrono {
                "chrono::DateTime<chrono::Utc>".into()
            } else {
                "String".into()
            }
        }
        "timestamp without time zone" | "timestamp" => {
            if opts.chrono {
                "chrono::NaiveDateTime".into()
            } else {
                "String".into()
            }
        }
        "date" => {
            if opts.chrono {
                "chrono::NaiveDate".into()
            } else {
                "String".into()
            }
        }
        "time with time zone" | "time without time zone" | "time" => "String".into(),
        // UUID
        "uuid" => {
            if opts.uuid_type {
                "uuid::Uuid".into()
            } else {
                "String".into()
            }
        }
        // JSON
        "json" | "jsonb" => "serde_json::Value".into(),
        // Bytes
        "bytea" => "Vec<u8>".into(),
        // Catch-all: use the OpenAPI `type` keyword
        _ => match kind {
            "string" => "String".into(),
            "integer" => "i64".into(),
            "number" => "f64".into(),
            "boolean" => "bool".into(),
            "array" => "Vec<serde_json::Value>".into(),
            "object" => "serde_json::Value".into(),
            _ => "serde_json::Value".into(),
        },
    }
}

/// Convert a `snake_case` table name into `PascalCase` for the struct name.
fn to_struct_name(table: &str) -> String {
    let mut out = String::with_capacity(table.len());
    let mut capitalize = true;
    for ch in table.chars() {
        if ch == '_' || ch == '-' || ch == ' ' {
            capitalize = true;
            continue;
        }
        if capitalize {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            capitalize = false;
        } else {
            out.push(ch);
        }
    }
    if out.is_empty() {
        out.push_str("Row");
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Sanitize a column name into a valid Rust field name. Reserved keywords
/// become `r#name`; non-identifier chars are replaced with `_`.
fn to_field_name(col: &str) -> String {
    let cleaned: String = col
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    let cleaned = if cleaned
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_digit())
    {
        format!("_{cleaned}")
    } else {
        cleaned
    };
    if is_rust_keyword(&cleaned) {
        format!("r#{cleaned}")
    } else {
        cleaned
    }
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
            | "union"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> OpenApi {
        let json = serde_json::json!({
            "definitions": {
                "users": {
                    "required": ["id", "email"],
                    "properties": {
                        "id":         { "format": "uuid", "type": "string" },
                        "email":      { "format": "text", "type": "string" },
                        "age":        { "format": "integer", "type": "integer" },
                        "created_at": { "format": "timestamp with time zone", "type": "string" },
                        "metadata":   { "format": "jsonb", "type": "object" },
                        "score":      { "format": "double precision", "type": "number" },
                        "type":       { "format": "text", "type": "string" }
                    }
                },
                "audit_log": {
                    "required": [],
                    "properties": {
                        "id":   { "format": "bigint", "type": "integer" },
                        "data": { "format": "json", "type": "object" }
                    }
                }
            }
        });
        serde_json::from_value(json).unwrap()
    }

    #[test]
    fn struct_naming() {
        assert_eq!(to_struct_name("users"), "Users");
        assert_eq!(to_struct_name("audit_log"), "AuditLog");
        assert_eq!(to_struct_name("2fa_tokens"), "_2faTokens");
    }

    #[test]
    fn keyword_columns_get_raw_prefix() {
        assert_eq!(to_field_name("type"), "r#type");
        assert_eq!(to_field_name("self"), "r#self");
        assert_eq!(to_field_name("normal"), "normal");
    }

    #[test]
    fn map_type_chrono_timestamp() {
        let col = ColumnDef {
            format: Some("timestamp with time zone".into()),
            kind: Some("string".into()),
            description: None,
        };
        let opts = Options { chrono: true, ..Options::default() };
        assert_eq!(map_type(&col, &opts), "chrono::DateTime<chrono::Utc>");

        let opts2 = Options { chrono: false, ..Options::default() };
        assert_eq!(map_type(&col, &opts2), "String");
    }

    #[test]
    fn map_type_uuid_optin() {
        let col = ColumnDef {
            format: Some("uuid".into()),
            kind: Some("string".into()),
            description: None,
        };
        let off = Options::default();
        assert_eq!(map_type(&col, &off), "String");

        let on = Options { uuid_type: true, ..Options::default() };
        assert_eq!(map_type(&col, &on), "uuid::Uuid");
    }

    #[test]
    fn emit_renders_required_vs_optional() {
        let opts = Options::default();
        let out = emit(&fixture(), &opts);

        // Required fields are NOT wrapped in Option.
        assert!(out.contains("pub email: String,"), "missing required email field:\n{out}");
        // Non-required fields ARE wrapped in Option.
        // Postgres `integer` is int4 → i32.
        assert!(out.contains("pub age: Option<i32>,"), "expected Option<i32> for age:\n{out}");
        // Timestamps map through chrono.
        assert!(out.contains("Option<chrono::DateTime<chrono::Utc>>"));
        // jsonb columns map to serde_json::Value.
        assert!(out.contains("Option<serde_json::Value>"));
        // Reserved keywords get r# prefix and serde rename.
        assert!(out.contains("#[serde(rename = \"type\")]"));
        assert!(out.contains("pub r#type: Option<String>,"));
        // Row impl with table + columns
        assert!(out.contains("impl Row for Users"));
        assert!(out.contains("const TABLE: &'static str = \"users\";"));
        assert!(out.contains("const SCHEMA: Option<&'static str> = Some(\"public\");"));
        // Alphabetical struct order: AuditLog comes before Users.
        let audit_pos = out.find("struct AuditLog").unwrap();
        let users_pos = out.find("struct Users").unwrap();
        assert!(audit_pos < users_pos, "expected AuditLog before Users");
    }

    #[test]
    fn only_filter_keeps_subset() {
        let opts = Options { only: vec!["users".into()], ..Options::default() };
        let out = emit(&fixture(), &opts);
        assert!(out.contains("struct Users"));
        assert!(!out.contains("struct AuditLog"));
    }

    #[test]
    fn exclude_filter_drops_subset() {
        let opts = Options { exclude: vec!["audit_log".into()], ..Options::default() };
        let out = emit(&fixture(), &opts);
        assert!(out.contains("struct Users"));
        assert!(!out.contains("struct AuditLog"));
    }

    // -----------------------------------------------------------------------
    // to_struct_name — comprehensive
    // -----------------------------------------------------------------------

    #[test]
    fn struct_name_single_word_lower() {
        assert_eq!(to_struct_name("posts"), "Posts");
    }

    #[test]
    fn struct_name_hyphenated() {
        assert_eq!(to_struct_name("blog-posts"), "BlogPosts");
    }

    #[test]
    fn struct_name_space_separated() {
        assert_eq!(to_struct_name("my table"), "MyTable");
    }

    #[test]
    fn struct_name_mixed_separators() {
        assert_eq!(to_struct_name("foo_bar-baz qux"), "FooBarBazQux");
    }

    #[test]
    fn struct_name_empty_becomes_row() {
        assert_eq!(to_struct_name(""), "Row");
    }

    #[test]
    fn struct_name_already_pascal() {
        // preserves original casing in subsequent chars
        assert_eq!(to_struct_name("UserProfiles"), "UserProfiles");
    }

    #[test]
    fn struct_name_digit_prefix_gets_underscore() {
        assert_eq!(to_struct_name("2fa"), "_2fa");
        assert_eq!(to_struct_name("0th_entry"), "_0thEntry");
    }

    // -----------------------------------------------------------------------
    // to_field_name — comprehensive
    // -----------------------------------------------------------------------

    #[test]
    fn field_name_plain_passes_through() {
        assert_eq!(to_field_name("user_id"), "user_id");
    }

    #[test]
    fn field_name_non_ident_chars_replaced() {
        assert_eq!(to_field_name("my-field"), "my_field");
        assert_eq!(to_field_name("field.name"), "field_name");
    }

    #[test]
    fn field_name_digit_start_gets_prefix() {
        assert_eq!(to_field_name("2ndcol"), "_2ndcol");
    }

    #[test]
    fn field_name_all_reserved_keywords() {
        // Spot-check a handful from both Rust editions
        let kws = ["as", "fn", "impl", "let", "mod", "mut", "pub", "ref",
                   "self", "struct", "trait", "type", "use", "where",
                   "async", "await", "dyn", "try", "union"];
        for kw in kws {
            let out = to_field_name(kw);
            assert_eq!(out, format!("r#{kw}"), "keyword {kw} should be prefixed");
        }
    }

    #[test]
    fn field_name_non_keyword_not_prefixed() {
        assert_eq!(to_field_name("normal"), "normal");
        assert_eq!(to_field_name("id"), "id");
        assert_eq!(to_field_name("value"), "value");
    }

    // -----------------------------------------------------------------------
    // map_type — all scalar formats
    // -----------------------------------------------------------------------

    fn mk(format: &str, kind: &str) -> ColumnDef {
        ColumnDef {
            format: if format.is_empty() { None } else { Some(format.to_string()) },
            kind: if kind.is_empty() { None } else { Some(kind.to_string()) },
            description: None,
        }
    }

    fn opts_default() -> Options { Options::default() }
    fn opts_no_chrono() -> Options { Options { chrono: false, ..Options::default() } }
    fn opts_uuid()     -> Options { Options { uuid_type: true, ..Options::default() } }

    // Integers
    #[test]
    fn map_smallint() {
        assert_eq!(map_type(&mk("smallint", "integer"), &opts_default()), "i16");
        assert_eq!(map_type(&mk("int2", "integer"), &opts_default()), "i16");
    }

    #[test]
    fn map_integer_variants() {
        for fmt in ["integer", "int", "int4", "serial"] {
            assert_eq!(map_type(&mk(fmt, "integer"), &opts_default()), "i32", "fmt={fmt}");
        }
    }

    #[test]
    fn map_bigint_variants() {
        for fmt in ["bigint", "int8", "bigserial"] {
            assert_eq!(map_type(&mk(fmt, "integer"), &opts_default()), "i64", "fmt={fmt}");
        }
    }

    // Floats
    #[test]
    fn map_real_and_float4() {
        assert_eq!(map_type(&mk("real", "number"), &opts_default()), "f32");
        assert_eq!(map_type(&mk("float4", "number"), &opts_default()), "f32");
    }

    #[test]
    fn map_double_precision() {
        assert_eq!(map_type(&mk("double precision", "number"), &opts_default()), "f64");
        assert_eq!(map_type(&mk("float8", "number"), &opts_default()), "f64");
    }

    #[test]
    fn map_numeric_decimal_money() {
        for fmt in ["numeric", "decimal", "money"] {
            assert_eq!(map_type(&mk(fmt, "number"), &opts_default()), "f64", "fmt={fmt}");
        }
    }

    // Boolean
    #[test]
    fn map_boolean() {
        assert_eq!(map_type(&mk("boolean", "boolean"), &opts_default()), "bool");
        assert_eq!(map_type(&mk("bool", "boolean"), &opts_default()), "bool");
    }

    // Strings
    #[test]
    fn map_text_string_variants() {
        for fmt in ["text", "character varying", "varchar", "character", "bpchar", "name", "citext"] {
            assert_eq!(map_type(&mk(fmt, "string"), &opts_default()), "String", "fmt={fmt}");
        }
    }

    // Timestamps with chrono
    #[test]
    fn map_timestamptz_with_chrono() {
        let col = mk("timestamp with time zone", "string");
        assert_eq!(map_type(&col, &opts_default()), "chrono::DateTime<chrono::Utc>");
        assert_eq!(map_type(&mk("timestamptz", "string"), &opts_default()), "chrono::DateTime<chrono::Utc>");
    }

    #[test]
    fn map_timestamptz_without_chrono() {
        assert_eq!(map_type(&mk("timestamp with time zone", "string"), &opts_no_chrono()), "String");
    }

    #[test]
    fn map_timestamp_naive_with_chrono() {
        assert_eq!(map_type(&mk("timestamp without time zone", "string"), &opts_default()), "chrono::NaiveDateTime");
        assert_eq!(map_type(&mk("timestamp", "string"), &opts_default()), "chrono::NaiveDateTime");
    }

    #[test]
    fn map_timestamp_naive_without_chrono() {
        assert_eq!(map_type(&mk("timestamp", "string"), &opts_no_chrono()), "String");
    }

    #[test]
    fn map_date_with_and_without_chrono() {
        assert_eq!(map_type(&mk("date", "string"), &opts_default()), "chrono::NaiveDate");
        assert_eq!(map_type(&mk("date", "string"), &opts_no_chrono()), "String");
    }

    #[test]
    fn map_time_is_always_string() {
        for fmt in ["time", "time with time zone", "time without time zone"] {
            assert_eq!(map_type(&mk(fmt, "string"), &opts_default()), "String", "fmt={fmt}");
            assert_eq!(map_type(&mk(fmt, "string"), &opts_no_chrono()), "String", "fmt={fmt} no-chrono");
        }
    }

    // UUID
    #[test]
    fn map_uuid_string_default() {
        assert_eq!(map_type(&mk("uuid", "string"), &opts_default()), "String");
    }

    #[test]
    fn map_uuid_type_with_flag() {
        assert_eq!(map_type(&mk("uuid", "string"), &opts_uuid()), "uuid::Uuid");
    }

    // JSON / JSONB
    #[test]
    fn map_json_jsonb() {
        assert_eq!(map_type(&mk("json", "object"), &opts_default()), "serde_json::Value");
        assert_eq!(map_type(&mk("jsonb", "object"), &opts_default()), "serde_json::Value");
    }

    // Bytea
    #[test]
    fn map_bytea() {
        assert_eq!(map_type(&mk("bytea", "string"), &opts_default()), "Vec<u8>");
    }

    // Arrays
    #[test]
    fn map_array_of_integer() {
        let col = ColumnDef {
            format: Some("integer".into()),
            kind: Some("array".into()),
            description: None,
        };
        assert_eq!(map_type(&col, &opts_default()), "Vec<i32>");
    }

    #[test]
    fn map_array_of_text() {
        let col = ColumnDef {
            format: Some("text".into()),
            kind: Some("array".into()),
            description: None,
        };
        assert_eq!(map_type(&col, &opts_default()), "Vec<String>");
    }

    #[test]
    fn map_array_of_uuid_with_flag() {
        let col = ColumnDef {
            format: Some("uuid".into()),
            kind: Some("array".into()),
            description: None,
        };
        assert_eq!(map_type(&col, &opts_uuid()), "Vec<uuid::Uuid>");
    }

    // Catch-all fallbacks
    #[test]
    fn map_unknown_format_falls_back_to_kind() {
        assert_eq!(map_type(&mk("unknown_pg_type", "string"), &opts_default()), "String");
        assert_eq!(map_type(&mk("unknown_pg_type", "integer"), &opts_default()), "i64");
        assert_eq!(map_type(&mk("unknown_pg_type", "number"), &opts_default()), "f64");
        assert_eq!(map_type(&mk("unknown_pg_type", "boolean"), &opts_default()), "bool");
        assert_eq!(map_type(&mk("unknown_pg_type", "object"), &opts_default()), "serde_json::Value");
    }

    #[test]
    fn map_totally_unknown_becomes_value() {
        assert_eq!(map_type(&mk("mystery_type", "mystery_kind"), &opts_default()), "serde_json::Value");
    }

    // -----------------------------------------------------------------------
    // emit — edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn emit_empty_definitions_contains_only_header() {
        let api = OpenApi { definitions: BTreeMap::new() };
        let out = emit(&api, &Options::default());
        assert!(out.contains("Auto-generated by"), "header should be present");
        assert!(!out.contains("pub struct"), "no structs should be emitted");
    }

    #[test]
    fn emit_custom_schema_baked_in() {
        let api = OpenApi {
            definitions: {
                let mut m = BTreeMap::new();
                m.insert("items".into(), TableDef {
                    required: vec!["id".into()],
                    properties: {
                        let mut p = BTreeMap::new();
                        p.insert("id".into(), mk("bigint", "integer"));
                        p
                    },
                });
                m
            },
        };
        let opts = Options { schema: "inventory".into(), ..Options::default() };
        let out = emit(&api, &opts);
        assert!(out.contains("const SCHEMA: Option<&'static str> = Some(\"inventory\");"));
        assert!(out.contains("/// Row of `inventory.items`"));
    }

    #[test]
    fn emit_bytea_column_type() {
        let api = OpenApi {
            definitions: {
                let mut m = BTreeMap::new();
                m.insert("blobs".into(), TableDef {
                    required: vec![],
                    properties: {
                        let mut p = BTreeMap::new();
                        p.insert("data".into(), mk("bytea", "string"));
                        p
                    },
                });
                m
            },
        };
        let out = emit(&api, &Options::default());
        assert!(out.contains("pub data: Option<Vec<u8>>,"), "bytea should map to Vec<u8>: {out}");
    }

    #[test]
    fn emit_column_with_description_emits_doc_comment() {
        let api = OpenApi {
            definitions: {
                let mut m = BTreeMap::new();
                m.insert("things".into(), TableDef {
                    required: vec!["id".into()],
                    properties: {
                        let mut p = BTreeMap::new();
                        p.insert("id".into(), ColumnDef {
                            format: Some("integer".into()),
                            kind: Some("integer".into()),
                            description: Some("Primary key".into()),
                        });
                        p
                    },
                });
                m
            },
        };
        let out = emit(&api, &Options::default());
        assert!(out.contains("/// Primary key"), "description should become doc comment: {out}");
    }

    #[test]
    fn emit_columns_sorted_alphabetically() {
        let api = OpenApi {
            definitions: {
                let mut m = BTreeMap::new();
                m.insert("t".into(), TableDef {
                    required: vec![],
                    properties: {
                        let mut p = BTreeMap::new();
                        p.insert("z_col".into(), mk("integer", "integer"));
                        p.insert("a_col".into(), mk("integer", "integer"));
                        p.insert("m_col".into(), mk("integer", "integer"));
                        p
                    },
                });
                m
            },
        };
        let out = emit(&api, &Options::default());
        let a = out.find("a_col").unwrap();
        let m = out.find("m_col").unwrap();
        let z = out.find("z_col").unwrap();
        assert!(a < m && m < z, "columns should appear in alphabetical order");
    }

    #[test]
    fn emit_only_and_exclude_both_set() {
        // `only` takes priority — "users" is in only, so audit_log is excluded
        // even though it's not in `exclude`.
        let opts = Options {
            only: vec!["users".into()],
            exclude: vec!["users".into()], // also in exclude
            ..Options::default()
        };
        let out = emit(&fixture(), &opts);
        // `only` matches users but `exclude` also contains it → excluded
        assert!(!out.contains("struct Users"), "excluded via both lists: {out}");
    }

    #[test]
    fn emit_no_tables_match_only_list() {
        let opts = Options { only: vec!["nonexistent".into()], ..Options::default() };
        let out = emit(&fixture(), &opts);
        assert!(!out.contains("pub struct"), "no structs should be emitted: {out}");
    }

    // -----------------------------------------------------------------------
    // OpenApi deserialization
    // -----------------------------------------------------------------------

    #[test]
    fn openapi_deserializes_missing_definitions() {
        let v = serde_json::json!({ "swagger": "2.0" });
        let api: OpenApi = serde_json::from_value(v).unwrap();
        assert!(api.definitions.is_empty());
    }

    #[test]
    fn openapi_deserializes_empty_definitions() {
        let v = serde_json::json!({ "definitions": {} });
        let api: OpenApi = serde_json::from_value(v).unwrap();
        assert!(api.definitions.is_empty());
    }

    #[test]
    fn table_def_required_defaults_empty() {
        let v = serde_json::json!({ "properties": {} });
        let t: TableDef = serde_json::from_value(v).unwrap();
        assert!(t.required.is_empty());
    }

    #[test]
    fn column_def_all_fields_optional() {
        let v = serde_json::json!({});
        let c: ColumnDef = serde_json::from_value(v).unwrap();
        assert!(c.format.is_none());
        assert!(c.kind.is_none());
        assert!(c.description.is_none());
    }

    // -----------------------------------------------------------------------
    // is_rust_keyword
    // -----------------------------------------------------------------------

    #[test]
    fn rust_keywords_recognized() {
        let keywords = ["as", "break", "const", "continue", "crate", "else", "enum",
                        "extern", "false", "fn", "for", "if", "impl", "in", "let",
                        "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
                        "self", "Self", "static", "struct", "super", "trait", "true",
                        "type", "unsafe", "use", "where", "while", "async", "await",
                        "dyn", "abstract", "become", "box", "do", "final", "macro",
                        "override", "priv", "typeof", "unsized", "virtual", "yield",
                        "try", "union"];
        for kw in keywords {
            assert!(is_rust_keyword(kw), "{kw} should be a keyword");
        }
    }

    #[test]
    fn non_keywords_not_recognized() {
        for name in ["id", "user", "data", "value", "name", "count", "email"] {
            assert!(!is_rust_keyword(name), "{name} should not be a keyword");
        }
    }

    // ----- typed column constants emission -----

    #[test]
    fn emit_includes_column_constants_block_per_table() {
        let out = emit(&fixture(), &Options::default());
        // Required column → bare type, no Option wrapper.
        assert!(
            out.contains("pub const email: Column<Users, String> = Column::new(\"email\");"),
            "missing column constant for email:\n{out}"
        );
        // Optional column → Option<T>.
        assert!(
            out.contains("pub const age: Column<Users, Option<i32>> = Column::new(\"age\");"),
            "missing optional column constant for age:\n{out}"
        );
        // Optional timestamp.
        assert!(
            out.contains(
                "pub const created_at: Column<Users, Option<chrono::DateTime<chrono::Utc>>> = Column::new(\"created_at\");"
            ),
            "missing optional timestamp column constant:\n{out}"
        );
        // Reserved keyword gets r# prefix on the const ident.
        assert!(
            out.contains("pub const r#type: Column<Users, Option<String>> = Column::new(\"type\");"),
            "expected r#type const with serde-renamed name:\n{out}"
        );
        // The impl block is opt-out for the lint.
        assert!(out.contains("#[allow(non_upper_case_globals)]"));
        // The block lives on the row struct itself.
        assert!(out.contains("impl Users {"));
    }

    #[test]
    fn emit_includes_column_import_in_header() {
        let out = emit(&fixture(), &Options::default());
        assert!(
            out.contains("use rust_supabase_sdk::{postgrest::Column, Row};"),
            "expected Column to be imported in the header:\n{out}"
        );
    }
}
