//! `cargo run --example postgrest_typed`
//!
//! Demonstrates the typed query path. Usually the `Row` impl below is
//! generated by `cargo supabase gen types`, but it's a five-line hand-impl
//! when you want to type just one or two tables.

use rust_supabase_sdk::{Row, SupabaseClient};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Country {
    pub id: i64,
    pub name: String,
    #[serde(default)]
    pub iso2: Option<String>,
}

impl Row for Country {
    const TABLE: &'static str = "countries";
    const COLUMNS: &'static [&'static str] = &["id", "name", "iso2"];
}

#[tokio::main]
async fn main() -> rust_supabase_sdk::Result<()> {
    let url = std::env::var("SUPABASE_URL").map_err(|_| {
        rust_supabase_sdk::SupabaseError::Unexpected("SUPABASE_URL not set".into())
    })?;
    let key = std::env::var("SUPABASE_API_KEY").map_err(|_| {
        rust_supabase_sdk::SupabaseError::Unexpected("SUPABASE_API_KEY not set".into())
    })?;

    let client = SupabaseClient::new(url, key, None);

    // Typed entry point — table name comes from the Row impl, response
    // deserializes straight into `Vec<Country>`.
    let countries: Vec<Country> = client
        .from_row::<Country>()
        .select(Country::COLUMNS.join(","))
        .order("name", true)
        .limit(5)
        .returns::<Country>()
        .await?;

    for c in countries {
        println!("{:>5}  {}  ({})", c.id, c.name, c.iso2.unwrap_or_default());
    }
    Ok(())
}
